import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })
import { register } from 'swiper/element/bundle'

register(); 
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/scrollbar'
import Provider from './Provider'

export const metadata = {
  title: 'Smart steps',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
       
      <body className={inter.className}>
        
        <Provider> 
       
          {children}
        
        </Provider>
      </body>
    </html>
  )
}
